local opt = vim.opt
local cmd = vim.cmd
local indent = 4

opt.number = true
opt.relativenumber = true
opt.tabstop = indent
opt.shiftwidth = indent
opt.softtabstop = indent
opt.expandtab = true
opt.autoindent = true
opt.smartindent = true
opt.ignorecase = true
opt.smartcase = true
opt.matchpairs = {"(:)", "{:}", "[:]", "<:>"}
opt.showmode = false
opt.cursorline = true
opt.termguicolors = true
opt.background = "dark"
opt.clipboard = "unnamedplus"
opt.hlsearch = true
opt.incsearch = true
opt.scrolloff = 10
opt.sidescrolloff = 10
opt.wrap = false
opt.list = true
opt.listchars = {
    tab = "┊ ",
    trail = "·",
    extends = "»",
    precedes = "«",
    nbsp = "×"
}
opt.cmdheight = 0
opt.mouse = "a"
opt.backup = false
opt.swapfile = false
opt.writebackup = false
opt.signcolumn = "yes"
opt.splitbelow = true
opt.splitright = true
